exports.up = knex => knex.schema.createTable('restaurants', (table) => {
  table.increments()
  table.string('name').notNullable().defaultTo('')
  table.string('img_url')
  table.float('rating')
  table.string('description')
  table.string('address').notNullable().defaultTo('')
  table.string('city').notNullable().defaultTo('')
  table.string('state_code').notNullable().defaultTo('')
  table.integer('postal_code').notNullable().defaultTo(0)
  table.string('yelp_id').notNullable().defaultTo('')
  table.integer('group_id')
    .notNullable()
    .defaultTo(0)
    .references('groups.id')
    .onDelete('CASCADE')
})

exports.down = knex => knex.schema.dropTable('restaurants')
