exports.seed = function (knex) {
  return knex('restaurants').del()
    .then(() => {
      return knex('restaurants').insert([
        {
          id: 1,
          name: 'Bluebird',
          img_url: '',
          rating: 4.5,
          description: '',
          address: '',
          city: '',
          state_code: '',
          postal_code: '',
          yelp_id: '',
          group_id: 1
        },
        {
          id: 2,
          name: 'Bluebird',
          img_url: '',
          rating: 4.5,
          description: '',
          address: '',
          city: '',
          state_code: '',
          postal_code: '',
          yelp_id: '',
          group_id: 1
        },
        {
          id: 3,
          name: 'Bluebird',
          img_url: '',
          rating: 4.5,
          description: '',
          address: '',
          city: '',
          state_code: '',
          postal_code: '',
          yelp_id: '',
          group_id: 1
        },
        {
          id: 4,
          name: 'Bluebird',
          img_url: '',
          rating: 4.5,
          description: '',
          address: '',
          city: '',
          state_code: '',
          postal_code: '',
          yelp_id: '',
          group_id: 1
        },
        {
          id: 5,
          name: 'Bluebird',
          img_url: '',
          rating: 4.5,
          description: '',
          address: '',
          city: '',
          state_code: '',
          postal_code: '',
          yelp_id: '',
          group_id: 1
        },
        {
          id: 6,
          name: 'Bluebird',
          img_url: '',
          rating: 4.5,
          description: '',
          address: '',
          city: '',
          state_code: '',
          postal_code: '',
          yelp_id: '',
          group_id: 1
        },
        {
          id: 7,
          name: 'Bluebird',
          img_url: '',
          rating: 4.5,
          description: '',
          address: '',
          city: '',
          state_code: '',
          postal_code: '',
          yelp_id: '',
          group_id: 1
        },
        {
          id: 8,
          name: 'Bluebird',
          img_url: '',
          rating: 4.5,
          description: '',
          address: '',
          city: '',
          state_code: '',
          postal_code: '',
          yelp_id: '',
          group_id: 1
        },
        {
          id: 9,
          name: 'Bluebird',
          img_url: '',
          rating: 4.5,
          description: '',
          address: '',
          city: '',
          state_code: '',
          postal_code: '',
          yelp_id: '',
          group_id: 1
        },
        {
          id: 10,
          name: 'Bluebird',
          img_url: '',
          rating: 4.5,
          description: '',
          address: '',
          city: '',
          state_code: '',
          postal_code: '',
          yelp_id: '',
          group_id: 1
        },
        {
          id: 11,
          name: 'Bluebird',
          img_url: '',
          rating: 4.5,
          description: '',
          address: '',
          city: '',
          state_code: '',
          postal_code: '',
          yelp_id: '',
          group_id: 1
        },
        {
          id: 12,
          name: 'Bluebird',
          img_url: '',
          rating: 4.5,
          description: '',
          address: '',
          city: '',
          state_code: '',
          postal_code: '',
          yelp_id: '',
          group_id: 1
        },
        {
          id: 13,
          name: 'Bluebird',
          img_url: '',
          rating: 4.5,
          description: '',
          address: '',
          city: '',
          state_code: '',
          postal_code: '',
          yelp_id: '',
          group_id: 1
        },
        {
          id: 14,
          name: 'Bluebird',
          img_url: '',
          rating: 4.5,
          description: '',
          address: '',
          city: '',
          state_code: '',
          postal_code: '',
          yelp_id: '',
          group_id: 1
        },
        {
          id: 15,
          name: 'Bluebird',
          img_url: '',
          rating: 4.5,
          description: '',
          address: '',
          city: '',
          state_code: '',
          postal_code: '',
          yelp_id: '',
          group_id: 1
        },
        {
          id: 16,
          name: 'Bluebird',
          img_url: '',
          rating: 4.5,
          description: '',
          address: '',
          city: '',
          state_code: '',
          postal_code: '',
          yelp_id: '',
          group_id: 1
        },
        {
          id: 17,
          name: 'Bluebird',
          img_url: '',
          rating: 4.5,
          description: '',
          address: '',
          city: '',
          state_code: '',
          postal_code: '',
          yelp_id: '',
          group_id: 1
        },
        {
          id: 18,
          name: 'Bluebird',
          img_url: '',
          rating: 4.5,
          description: '',
          address: '',
          city: '',
          state_code: '',
          postal_code: '',
          yelp_id: '',
          group_id: 1
        },
        {
          id: 19,
          name: 'Bluebird',
          img_url: '',
          rating: 4.5,
          description: '',
          address: '',
          city: '',
          state_code: '',
          postal_code: '',
          yelp_id: '',
          group_id: 1
        },
        {
          id: 20,
          name: 'Bluebird',
          img_url: '',
          rating: 4.5,
          description: '',
          address: '',
          city: '',
          state_code: '',
          postal_code: '',
          yelp_id: '',
          group_id: 1
        }
      ])
    })
    .then(() => {
      return knex.raw(
        "SELECT setval('restaurants_id_seq', (SELECT MAX(id) FROM restaurants));"
      )
    })
}
